apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api-service
spec:
  generators:
    - git:
        repoURL: https://github.com/SnehaTrimukhe123/devsecops-assessment.git
        revision: main
        directories:
          - path: /
  template:
    metadata:
      name: api-app
    spec:
      project: default
      source:
        repoURL: https://github.com/SnehaTrimukhe123/devsecops-assessment.git
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: api
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
